Repository jenkinsci/plain-credentials-plugin, pull requests merged in 2020-01, with the labels that each got.

#19 Remove trilead from credentials test
  src/test/java/org/jenkinsci/plugins/plaincredentials/BaseTest.java
Labels: chore

#16 Typo on Copyright notice
  pom.xml
Labels: bug, ready-to-merge

#17 Migrate docs from wiki to github
  CHANGELOG.md
  README.md
  docs/images/secretFile.png
  docs/images/secretText.png
  pom.xml
Labels: documentation, ready-to-merge

#18 [JENKINS-60718] Replace disclosure label with Replace
  src/main/resources/org/jenkinsci/plugins/plaincredentials/impl/FileCredentialsImpl/credentials.jelly
  src/main/resources/org/jenkinsci/plugins/plaincredentials/impl/FileCredentialsImpl/credentials.properties
Labels: ready-to-merge, rfe

#20 Upgrade to use jcasc test harness
  pom.xml
  src/test/java/org/jenkinsci/plugins/plaincredentials/ConfigurationAsCodeTest.java
Labels: chore, dependencies, ready-to-merge
