Repository jenkinsci/plain-credentials-plugin, pull requests merged in 2022-07, with the labels that each got.

#29 Move away from deprecated Release Drafter App
  .github/workflows/release-drafter.yml
Labels: enhancement

#30 Refresh plugin
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: maintenance

#31 Enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: developer
